### ISSUE TITLE
How to compress JavaScript of Automotive Theme

### ISSUE THREAD

**Issue by suzukisumberbaru** [mjawaids/automotive-feed-import#1]
http://suzukisumberbaru.com/wp-content/themes/automotive/js/retina.js

**Comment by mjawaids** [comment]
There are different Wordpress plugins available that you can use to minify any javascript. See this to start
https://wordpress.org/plugins/tags/minify/

**Comment by suzukisumberbaru** [comment]
I used W3 Total Cache in my site. But it doesn't work because I would check in Google Page Speed, there are found 3 Javascript rendered blocking :

http://suzukisumberbaru.com/wp-includes/js/jquery/jquery.js

http://suzukisumberbaru.com/wp-includes/js/jquery/jquery-migrate.min.js

http://suzukisumberbaru.com/wp-content/plugins/automotive/js/jquery-ui-1.10.3.custom.min.js

How should I do?

**Comment by mjawaids** [comment]
These seem to be already minified.
